name: hostapd-mahboi
version: '2.6'
summary: Hostapd as a snap; made for personal use.
description: |
  This is hostapd built as a snap. I'm using this for a personal
  project, thus it might not work for your uses. That's why you
  can fork it on github!

grade: devel 
confinement: devmode
type: os

#
# Known dependancies of hostapd
#	- libnl3 (https://www.infradead.org/~tgr/libnl/files/libnl-3.2.25.tar.gz)
#	- 
#

apps:
  hostapd:
    command: usr/local/bin/hostapd
    daemon: forking
    


parts:
  libnl1:
    plugin: autotools
    source: https://www.infradead.org/~tgr/libnl/files/libnl-1.1.4.tar.gz
  hostapd:
    source: https://w1.fi/releases/hostapd-2.6.tar.gz
    source-subdir: hostapd
    prepare: |
      cp hostapd/defconfig hostapd/.config # just for testing; replace with own config
    build-packages: 
      - libnl-3-dev
      - libnl-genl-3-dev
      - libssl-dev
    plugin: make
    makefile: Makefile
#    build: |
#      cd hostapd
#      make -f Makefile -j$(nproc)
#    make-install-var: ../../../../stage
#      - hostapd/hostapd
#      - hostapd/hostapd-cli
    after: [libnl1]


