name: hostapd-mahboi
version: '2.6'
summary: Hostapd as a snap; made for personal use.
description: |
  This is hostapd built as a snap. I'm using this for a personal
  project, thus it might not work for your uses. That's why you
  can fork it on github!

grade: devel 
confinement: devmode
type: core

#
# Known dependancies of hostapd
#	- libnl3 (https://www.infradead.org/~tgr/libnl/files/libnl-3.2.25.tar.gz)
#	- 
#

parts:
  hostapd:
	plugin: # needs configuration, uses kbuild-style
	source: https://w1.fi/releases/hostapd-2.6.tar.gz
	source-subdir: hostapd
	build-packages: 
		- libnl3-dev
		- libnl-genl-3-dev
		- libssl-dev


